/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.funcionarioDao;
import modeloBeans.modeloFuncionario;
import persistencia.ConexaoSQL;

/**
 *
 * @author joaov
 */
public class cadastrofuncionarios extends javax.swing.JFrame {
    modeloFuncionario modFun = new modeloFuncionario();
    funcionarioDao funDao = new funcionarioDao();
    ConexaoSQL connex = new ConexaoSQL();

    /**
     * Creates new form cadastrofuncionarios
     */
    public cadastrofuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kComboBox1 = new br.com.cyber.componente.KComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome_func = new javax.swing.JTextField();
        end_func = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktable1 = new br.com.cyber.componente.Ktable();
        jLabel5 = new javax.swing.JLabel();
        FuncionarioPesquisa = new javax.swing.JTextField();
        kButton1 = new br.com.cyber.componente.KButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel1.setText("telefone");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 215, 104, 35);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 103, 104, 35);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel3.setText("cpf");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(41, 156, 104, 35);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(41, 273, 104, 35);

        nome_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_funcActionPerformed(evt);
            }
        });
        getContentPane().add(nome_func);
        nome_func.setBounds(150, 103, 323, 35);

        end_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_funcActionPerformed(evt);
            }
        });
        getContentPane().add(end_func);
        end_func.setBounds(150, 273, 323, 35);

        ktable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ktable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(529, 121, 452, 355);

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 48)); // NOI18N
        jLabel5.setText("Funcionários");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(41, 13, 316, 61);
        getContentPane().add(FuncionarioPesquisa);
        FuncionarioPesquisa.setBounds(529, 40, 301, 38);

        kButton1.setBackground(new java.awt.Color(51, 255, 0));
        kButton1.setText("Busca");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(837, 40, 100, 34);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 156, 323, 35);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 209, 323, 32);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("INSERIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 350, 110, 31);

        setSize(new java.awt.Dimension(1038, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nome_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_funcActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nome_funcActionPerformed

    private void end_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_funcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_funcActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrofuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrofuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrofuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrofuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrofuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FuncionarioPesquisa;
    private javax.swing.JTextField end_func;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private br.com.cyber.componente.KButton kButton1;
    private br.com.cyber.componente.KComboBox kComboBox1;
    private br.com.cyber.componente.Ktable ktable1;
    private javax.swing.JTextField nome_func;
    // End of variables declaration//GEN-END:variables
}
