/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import modeloBeans.modeloFuncionario;
import dao.funcionarioDao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import persistencia.ConexaoSQL;

/**
 *
 * @author joaov
 */
public class funcionario extends javax.swing.JFrame {
    ConexaoSQL connex = new ConexaoSQL();
    funcionarioDao daoFunc = new funcionarioDao();
    modeloFuncionario modFunc = new modeloFuncionario();
    int flag =0;

    /**
     * Creates new form funcionario
     */
    public funcionario() {
        initComponents();
        connex.conexao();
        preencherTabela("select * from funcionario order by codigo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telefoneFUNCIONARIO = new javax.swing.JTextField();
        enderecoFUNCIONARIO = new javax.swing.JTextField();
        nomeFUNCIONARIO = new javax.swing.JTextField();
        cpfFUNCIONARIO = new javax.swing.JTextField();
        codFUNCIONARIO = new javax.swing.JTextField();
        botaoINSERIR = new javax.swing.JButton();
        botaoBuscar = new br.com.cyber.componente.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new br.com.cyber.componente.Ktable();
        botaoNOVO = new javax.swing.JButton();
        botaoCANCELAR = new javax.swing.JButton();
        botaoEDITAR = new javax.swing.JButton();
        botaoEXCLUIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pesquiseFUNCIONARIO = new br.com.cyber.componente.KTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Funcionário");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Telefone:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Endereço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Código:");

        telefoneFUNCIONARIO.setEnabled(false);

        enderecoFUNCIONARIO.setEnabled(false);

        nomeFUNCIONARIO.setEnabled(false);

        cpfFUNCIONARIO.setEnabled(false);

        codFUNCIONARIO.setEnabled(false);

        botaoINSERIR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoINSERIR.setText("INSERIR");
        botaoINSERIR.setEnabled(false);
        botaoINSERIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoINSERIRActionPerformed(evt);
            }
        });

        botaoBuscar.setBackground(new java.awt.Color(0, 255, 0));
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionario);

        botaoNOVO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoNOVO.setText("NOVO");
        botaoNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNOVOActionPerformed(evt);
            }
        });

        botaoCANCELAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCANCELAR.setText("CANCELAR");
        botaoCANCELAR.setEnabled(false);
        botaoCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCANCELARActionPerformed(evt);
            }
        });

        botaoEDITAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEDITAR.setText("EDITAR");
        botaoEDITAR.setEnabled(false);
        botaoEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEDITARActionPerformed(evt);
            }
        });

        botaoEXCLUIR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEXCLUIR.setText("EXCLUIR");
        botaoEXCLUIR.setEnabled(false);
        botaoEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEXCLUIRActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Desktop\\icone_prrincipal.png")); // NOI18N

        pesquiseFUNCIONARIO.setK_placeholder_text("Pesquise funcionário por nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48)
                                .addComponent(nomeFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enderecoFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(codFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(botaoINSERIR)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pesquiseFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botaoNOVO)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCANCELAR)
                                .addGap(18, 18, 18)
                                .addComponent(botaoEDITAR)
                                .addGap(18, 18, 18)
                                .addComponent(botaoEXCLUIR))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquiseFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoNOVO)
                            .addComponent(botaoCANCELAR)
                            .addComponent(botaoEDITAR)
                            .addComponent(botaoEXCLUIR))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nomeFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cpfFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(enderecoFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(telefoneFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(codFUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoINSERIR)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoINSERIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoINSERIRActionPerformed
        // TODO add your handling code here:
        if(flag==1){
        modFunc.setTelefone(Long.parseLong(telefoneFUNCIONARIO.getText()));
        modFunc.setEndereco(enderecoFUNCIONARIO.getText());
        modFunc.setNome(nomeFUNCIONARIO.getText());
        modFunc.setCpf(Long.parseLong(cpfFUNCIONARIO.getText()));
        daoFunc.Salvar(modFunc);
        telefoneFUNCIONARIO.setText("");
        enderecoFUNCIONARIO.setText("");
        nomeFUNCIONARIO.setText("");
        cpfFUNCIONARIO.setText("");
        codFUNCIONARIO.setText("");
        botaoINSERIR.setEnabled(false);
        telefoneFUNCIONARIO.setEnabled(false);
        enderecoFUNCIONARIO.setEnabled(false);
        nomeFUNCIONARIO.setEnabled(false);
        cpfFUNCIONARIO.setEnabled(false);
        }else{
            modFunc.setCodigo(Integer.parseInt(codFUNCIONARIO.getText()));
            modFunc.setTelefone(Long.parseLong(telefoneFUNCIONARIO.getText()));
            modFunc.setCpf(Long.parseLong(cpfFUNCIONARIO.getText()));
            modFunc.setEndereco(enderecoFUNCIONARIO.getText());
            modFunc.setNome(nomeFUNCIONARIO.getText());
            daoFunc.editarCliente(modFunc);
            botaoINSERIR.setEnabled(false);
            nomeFUNCIONARIO.setEnabled(false);
            cpfFUNCIONARIO.setEnabled(false);
            enderecoFUNCIONARIO.setEnabled(false);
            telefoneFUNCIONARIO.setEnabled(false);
        }
    }//GEN-LAST:event_botaoINSERIRActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        // TODO add your handling code here:
        modFunc.setPesquisa(pesquiseFUNCIONARIO.getText());
        modeloFuncionario model = daoFunc.buscaFuncionario(modFunc);
        telefoneFUNCIONARIO.setText(String.valueOf(model.getTelefone()));
        enderecoFUNCIONARIO.setText(String.valueOf(model.getEndereco()));
        nomeFUNCIONARIO.setText(model.getNome());
        telefoneFUNCIONARIO.setText(String.valueOf(model.getTelefone()));
        cpfFUNCIONARIO.setText(String.valueOf(model.getCpf()));
        codFUNCIONARIO.setText(String.valueOf(model.getCodigo()));
        botaoEDITAR.setEnabled(true);
        botaoEXCLUIR.setEnabled(true);
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNOVOActionPerformed
        // TODO add your handling code here:
         botaoINSERIR.setEnabled(true);
        telefoneFUNCIONARIO.setEnabled(true);
        enderecoFUNCIONARIO.setEnabled(true);
        nomeFUNCIONARIO.setEnabled(true);
        cpfFUNCIONARIO.setEnabled(true);
        botaoCANCELAR.setEnabled(true);
        telefoneFUNCIONARIO.setText("");
        enderecoFUNCIONARIO.setText("");
        nomeFUNCIONARIO.setText("");
        cpfFUNCIONARIO.setText("");
        codFUNCIONARIO.setText("");
    }//GEN-LAST:event_botaoNOVOActionPerformed

    private void tabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionarioMouseClicked
        // TODO add your handling code here:
        int indice = tabelaFuncionario.getSelectedRow();
        telefoneFUNCIONARIO.setText(tabelaFuncionario.getValueAt(indice, 4).toString());
        enderecoFUNCIONARIO.setText(tabelaFuncionario.getValueAt(indice, 3).toString());
        nomeFUNCIONARIO.setText(tabelaFuncionario.getValueAt(indice, 1).toString());
        cpfFUNCIONARIO.setText(tabelaFuncionario.getValueAt(indice, 2).toString());
        codFUNCIONARIO.setText(tabelaFuncionario.getValueAt(indice, 0).toString());
        botaoEDITAR.setEnabled(true);
        botaoEXCLUIR.setEnabled(true);
        botaoCANCELAR.setEnabled(true);
    }//GEN-LAST:event_tabelaFuncionarioMouseClicked

    private void botaoCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCANCELARActionPerformed
        // TODO add your handling code here:
        botaoINSERIR.setEnabled(false);
        telefoneFUNCIONARIO.setEnabled(false);
        enderecoFUNCIONARIO.setEnabled(false);
        nomeFUNCIONARIO.setEnabled(false);
        cpfFUNCIONARIO.setEnabled(false);
        telefoneFUNCIONARIO.setText("");
        enderecoFUNCIONARIO.setText("");
        nomeFUNCIONARIO.setText("");
        cpfFUNCIONARIO.setText("");
        codFUNCIONARIO.setText("");
    }//GEN-LAST:event_botaoCANCELARActionPerformed

    private void botaoEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEXCLUIRActionPerformed
        // TODO add your handling code here:
        int resposta =0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION){
            modFunc.setCodigo(Integer.parseInt(codFUNCIONARIO.getText()));
            daoFunc.excluirCliente(modFunc);
        }
    }//GEN-LAST:event_botaoEXCLUIRActionPerformed

    private void botaoEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEDITARActionPerformed
        // TODO add your handling code here:
        flag=2;
        telefoneFUNCIONARIO.setEnabled(true);
        cpfFUNCIONARIO.setEnabled(true);
        nomeFUNCIONARIO.setEnabled(true);
        enderecoFUNCIONARIO.setEnabled(true);
        botaoINSERIR.setEnabled(true);
    }//GEN-LAST:event_botaoEDITARActionPerformed

    /**
     * @param args the command line arguments
     */  
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"codigo", "nome", "cpf", "endereco", "telefone"};
        connex.conexao();
        
        connex.executaSql(Sql);
         try {
            connex.rs.first();
            do {
                dados.add(new Object[]{connex.rs.getInt("codigo"), connex.rs.getString("nome"), connex.rs.getLong("cpf"), connex.rs.getString("endereco"), connex.rs.getLong("telefone")});
            } while (connex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro produto na tabela" +ex);
            
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        tabelaFuncionario.setModel(modelo);
        tabelaFuncionario.getColumnModel().getColumn(0).setPreferredWidth(70);
        tabelaFuncionario.getColumnModel().getColumn(0).setResizable(false);
        tabelaFuncionario.getColumnModel().getColumn(1).setPreferredWidth(160);
        tabelaFuncionario.getColumnModel().getColumn(1).setResizable(false);
        tabelaFuncionario.getColumnModel().getColumn(2).setPreferredWidth(130);
        tabelaFuncionario.getColumnModel().getColumn(2).setResizable(false);
        tabelaFuncionario.getColumnModel().getColumn(3).setPreferredWidth(180);
        tabelaFuncionario.getColumnModel().getColumn(3).setResizable(false);
        tabelaFuncionario.getColumnModel().getColumn(4).setPreferredWidth(130);
        tabelaFuncionario.getColumnModel().getColumn(4).setResizable(false);
        
        
        tabelaFuncionario.setAutoResizeMode(tabelaFuncionario.AUTO_RESIZE_OFF);
        tabelaFuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connex.desconecta();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.cyber.componente.KButton botaoBuscar;
    private javax.swing.JButton botaoCANCELAR;
    private javax.swing.JButton botaoEDITAR;
    private javax.swing.JButton botaoEXCLUIR;
    private javax.swing.JButton botaoINSERIR;
    private javax.swing.JButton botaoNOVO;
    private javax.swing.JTextField codFUNCIONARIO;
    private javax.swing.JTextField cpfFUNCIONARIO;
    private javax.swing.JTextField enderecoFUNCIONARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeFUNCIONARIO;
    private br.com.cyber.componente.KTextField pesquiseFUNCIONARIO;
    private br.com.cyber.componente.Ktable tabelaFuncionario;
    private javax.swing.JTextField telefoneFUNCIONARIO;
    // End of variables declaration//GEN-END:variables
}
