/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.caixa_diario;
import persistencia.ConexaoSQL;

/**
 *
 * @author joaov
 */
public class tela_principal extends javax.swing.JFrame {
    ConexaoSQL conecta = new ConexaoSQL();

    /**
     * Creates new form tela_principal
     */
    public tela_principal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        func3 = new javax.swing.JButton();
        func2 = new javax.swing.JButton();
        func1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        func = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        func6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        func3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shoppaymentorderbuy-29_icon-icons.com_73875.png"))); // NOI18N
        func3.setToolTipText("Venda");
        func3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func3ActionPerformed(evt);
            }
        });
        getContentPane().add(func3);
        func3.setBounds(580, 490, 140, 120);

        func2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cash-money_icon-icons.com_74204.png"))); // NOI18N
        func2.setToolTipText("Pagamento");
        func2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func2ActionPerformed(evt);
            }
        });
        getContentPane().add(func2);
        func2.setBounds(1010, 240, 140, 120);

        func1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func1.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Desktop\\shoppingcart_compra_13339.png")); // NOI18N
        func1.setToolTipText("Compra");
        func1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func1ActionPerformed(evt);
            }
        });
        getContentPane().add(func1);
        func1.setBounds(1090, 60, 140, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 150, 250, 300);

        func.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Funcionário homem-80.png")); // NOI18N
        func.setToolTipText("Funcionários");
        func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcActionPerformed(evt);
            }
        });
        getContentPane().add(func);
        func.setBounds(50, 60, 140, 120);

        clientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Empresa Cliente-128.png")); // NOI18N
        clientes.setToolTipText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        getContentPane().add(clientes);
        clientes.setBounds(120, 230, 140, 130);

        func6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cashier_icon-icons.com_53629.png"))); // NOI18N
        func6.setToolTipText("Caixa Diário");
        func6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func6ActionPerformed(evt);
            }
        });
        getContentPane().add(func6);
        func6.setBounds(910, 440, 140, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Mover por carrinho-100.png")); // NOI18N
        jButton2.setToolTipText("Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 450, 133, 130);

        jLabel4.setFont(new java.awt.Font("Vladimir Script", 3, 75)); // NOI18N
        jLabel4.setText("Bem - Vindo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 60, 400, 92);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Desktop\\Sem Título-1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 700);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Desktop\\Sem Título-1.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 700);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 170, 41, 16);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Padaria");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcActionPerformed
        // TODO add your handling code here:
        funcionario funcionario = new funcionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_funcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cadastropodruto produto = new cadastropodruto();
        produto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        cliente cliente = new cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        usuario usuariotela = new usuario();
        usuariotela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void func1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func1ActionPerformed
        // TODO add your handling code here:
        compra cpr = new compra();
        cpr.setVisible(true);
    }//GEN-LAST:event_func1ActionPerformed

    private void func2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func2ActionPerformed
        // TODO add your handling code here:
        pagamento pgmnt = new pagamento();
        pgmnt. setVisible(true);
    }//GEN-LAST:event_func2ActionPerformed

    private void func3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func3ActionPerformed
        // TODO add your handling code here:
        venda vnd = new venda();
        vnd.setVisible(true);
    }//GEN-LAST:event_func3ActionPerformed

    private void func6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func6ActionPerformed
        // TODO add your handling code here:
        CaicaDiario caixaD = new CaicaDiario();
        caixaD.setVisible(true);
    }//GEN-LAST:event_func6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        padaria padaria = new padaria();
        padaria.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientes;
    private javax.swing.JButton func;
    private javax.swing.JButton func1;
    private javax.swing.JButton func2;
    private javax.swing.JButton func3;
    private javax.swing.JButton func6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
