/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author joaov
 */
public class tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form tela_principal
     */
    public tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        func = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 63)); // NOI18N
        jLabel1.setText("Manutenção");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 390, 102);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 240, 250, 300);

        func.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        func.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Funcionário homem-80.png")); // NOI18N
        func.setToolTipText("Funcionários");
        func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcActionPerformed(evt);
            }
        });
        getContentPane().add(func);
        func.setBounds(140, 190, 140, 120);

        clientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Empresa Cliente-128.png")); // NOI18N
        clientes.setToolTipText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        getContentPane().add(clientes);
        clientes.setBounds(140, 350, 140, 130);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Downloads\\icons8-Mover por carrinho-100.png")); // NOI18N
        jButton2.setToolTipText("Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 510, 133, 130);

        jLabel4.setFont(new java.awt.Font("Vladimir Script", 3, 75)); // NOI18N
        jLabel4.setText("Bem - Vindo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 160, 400, 92);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaov\\Desktop\\Sem Título-1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcActionPerformed
        // TODO add your handling code here:
        cadastrofuncionarios funcionario = new cadastrofuncionarios();
        funcionario.setVisible(true);
    }//GEN-LAST:event_funcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cadastropodruto produto = new cadastropodruto();
        produto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        cadastrocliente cliente = new cadastrocliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientes;
    private javax.swing.JButton func;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
